# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa3baedf952f6f6cdd4957fd17333a91438b017bdd19b0e9bd118a8b69d0ea8213e488eb49506c39c4e04789b6aa5479a1be62d5c636182381ddb8dcb5bb4fbc

test:
  secret_key_base: 968ed82c658213f322e4e0044062986704e2202f8425485ff4e88925d4e2b3c253ef23b39aa8db384ca4402981b52d5bfef82a005623dd42ba8bc6b1b2e4a0ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
